apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $name, $value := .Values.env.secret }}
  {{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}