{{- if .Values.serviceAccountRoleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.fullname" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccountRoleArn }}
{{- end }}