apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.healthPath }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: {{ .Values.appPort }}
      protocol: TCP
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
